### ISSUE TITLE
error

### ISSUE THREAD

**Issue by zhuyanchen116** [cran/rcssci#1]
> rcssci_cox(data=sbpdata, y = "status",x = "sbp",covs=c("age","gender"),time = "time", prob=0.1,filepath = "./")
Error in reformulate(attr(termobj, "term.labels")[-dropx], response = if (keep.response) termobj[[2L]],  : 
  'termlabels'必需是长度至少为一的字节矢量

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!
